/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package swc.microservice.truck

import io.kotest.core.spec.style.FreeSpec

class TruckManagerTest : FreeSpec({

    "The truck manager" - {
        "when communicating with Azure Digital Twins" - {
            "should fetch a model" {

            }
        }
    }
})
